swagger: '2.0'
info:
  title: HTTP API Console warden.intent
  name: ''
  description: ''
paths:
  /wardenprotocol/warden/intent/actions:
    get:
      operationId: Query_Actions
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
              actions:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uint64
                    approvers:
                      type: array
                      items:
                        type: string
                    status:
                      type: string
                      enum:
                        - ACTION_STATUS_UNSPECIFIED
                        - ACTION_STATUS_PENDING
                        - ACTION_STATUS_COMPLETED
                        - ACTION_STATUS_REVOKED
                        - ACTION_STATUS_TIMEOUT
                      default: ACTION_STATUS_UNSPECIFIED
                    intent_id:
                      type: string
                      format: uint64
                    msg:
                      type: object
                      properties:
                        '@type':
                          type: string
                      additionalProperties: {}
                    creator:
                      type: string
                    btl:
                      type: string
                      format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /wardenprotocol/warden/intent/actions_by_address:
    get:
      operationId: Query_ActionsByAddress
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
              actions:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uint64
                    approvers:
                      type: array
                      items:
                        type: string
                    status:
                      type: string
                      enum:
                        - ACTION_STATUS_UNSPECIFIED
                        - ACTION_STATUS_PENDING
                        - ACTION_STATUS_COMPLETED
                        - ACTION_STATUS_REVOKED
                        - ACTION_STATUS_TIMEOUT
                      default: ACTION_STATUS_UNSPECIFIED
                    intent_id:
                      type: string
                      format: uint64
                    msg:
                      type: object
                      properties:
                        '@type':
                          type: string
                      additionalProperties: {}
                    creator:
                      type: string
                    btl:
                      type: string
                      format: uint64
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
        - name: address
          in: query
          required: false
          type: string
        - name: status
          description: |2-
             - ACTION_STATUS_UNSPECIFIED: Unspecified status.
             - ACTION_STATUS_PENDING: Action is pending approval. This is the initial status.
             - ACTION_STATUS_COMPLETED: Intent has been satified, action has been executed.
             - ACTION_STATUS_REVOKED: Action has been revoked by its creator.
             - ACTION_STATUS_TIMEOUT: Action has been rejected since Btl is expired
          in: query
          required: false
          type: string
          enum:
            - ACTION_STATUS_UNSPECIFIED
            - ACTION_STATUS_PENDING
            - ACTION_STATUS_COMPLETED
            - ACTION_STATUS_REVOKED
            - ACTION_STATUS_TIMEOUT
          default: ACTION_STATUS_UNSPECIFIED
      tags:
        - Query
  /wardenprotocol/warden/intent/intent_by_id:
    get:
      operationId: Query_IntentById
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              intent:
                type: object
                properties:
                  intent:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uint64
                      name:
                        type: string
                      intent:
                        type: object
                        properties:
                          '@type':
                            type: string
                        additionalProperties: {}
                  metadata:
                    type: object
                    properties:
                      '@type':
                        type: string
                    additionalProperties: {}
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: id
          in: query
          required: false
          type: string
          format: uint64
      tags:
        - Query
  /wardenprotocol/warden/intent/intents:
    get:
      operationId: Query_Intents
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              pagination:
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                  total:
                    type: string
                    format: uint64
              intents:
                type: array
                items:
                  type: object
                  properties:
                    intent:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uint64
                        name:
                          type: string
                        intent:
                          type: object
                          properties:
                            '@type':
                              type: string
                          additionalProperties: {}
                    metadata:
                      type: object
                      properties:
                        '@type':
                          type: string
                      additionalProperties: {}
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: pagination.key
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /wardenprotocol/warden/intent/params:
    get:
      operationId: Query_Params
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                type: object
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - Query
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
  Action:
    type: object
    properties:
      id:
        type: string
        format: uint64
      approvers:
        type: array
        items:
          type: string
      status:
        type: string
        enum:
          - ACTION_STATUS_UNSPECIFIED
          - ACTION_STATUS_PENDING
          - ACTION_STATUS_COMPLETED
          - ACTION_STATUS_REVOKED
          - ACTION_STATUS_TIMEOUT
        default: ACTION_STATUS_UNSPECIFIED
      intent_id:
        type: string
        format: uint64
      msg:
        type: object
        properties:
          '@type':
            type: string
        additionalProperties: {}
      creator:
        type: string
      btl:
        type: string
        format: uint64
  ActionStatus:
    type: string
    enum:
      - ACTION_STATUS_UNSPECIFIED
      - ACTION_STATUS_PENDING
      - ACTION_STATUS_COMPLETED
      - ACTION_STATUS_REVOKED
      - ACTION_STATUS_TIMEOUT
    default: ACTION_STATUS_UNSPECIFIED
  Intent:
    type: object
    properties:
      id:
        type: string
        format: uint64
      name:
        type: string
      intent:
        type: object
        properties:
          '@type':
            type: string
        additionalProperties: {}
  IntentResponse:
    type: object
    properties:
      intent:
        type: object
        properties:
          id:
            type: string
            format: uint64
          name:
            type: string
          intent:
            type: object
            properties:
              '@type':
                type: string
            additionalProperties: {}
      metadata:
        type: object
        properties:
          '@type':
            type: string
        additionalProperties: {}
  PageRequest:
    type: object
    properties:
      key:
        type: string
        format: byte
      offset:
        type: string
        format: uint64
      limit:
        type: string
        format: uint64
      count_total:
        type: boolean
      reverse:
        type: boolean
  PageResponse:
    type: object
    properties:
      next_key:
        type: string
        format: byte
      total:
        type: string
        format: uint64
  Params:
    type: object
  QueryActionsByAddressResponse:
    type: object
    properties:
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
      actions:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              format: uint64
            approvers:
              type: array
              items:
                type: string
            status:
              type: string
              enum:
                - ACTION_STATUS_UNSPECIFIED
                - ACTION_STATUS_PENDING
                - ACTION_STATUS_COMPLETED
                - ACTION_STATUS_REVOKED
                - ACTION_STATUS_TIMEOUT
              default: ACTION_STATUS_UNSPECIFIED
            intent_id:
              type: string
              format: uint64
            msg:
              type: object
              properties:
                '@type':
                  type: string
              additionalProperties: {}
            creator:
              type: string
            btl:
              type: string
              format: uint64
  QueryActionsResponse:
    type: object
    properties:
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
      actions:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              format: uint64
            approvers:
              type: array
              items:
                type: string
            status:
              type: string
              enum:
                - ACTION_STATUS_UNSPECIFIED
                - ACTION_STATUS_PENDING
                - ACTION_STATUS_COMPLETED
                - ACTION_STATUS_REVOKED
                - ACTION_STATUS_TIMEOUT
              default: ACTION_STATUS_UNSPECIFIED
            intent_id:
              type: string
              format: uint64
            msg:
              type: object
              properties:
                '@type':
                  type: string
              additionalProperties: {}
            creator:
              type: string
            btl:
              type: string
              format: uint64
  QueryIntentByIdResponse:
    type: object
    properties:
      intent:
        type: object
        properties:
          intent:
            type: object
            properties:
              id:
                type: string
                format: uint64
              name:
                type: string
              intent:
                type: object
                properties:
                  '@type':
                    type: string
                additionalProperties: {}
          metadata:
            type: object
            properties:
              '@type':
                type: string
            additionalProperties: {}
  QueryIntentsResponse:
    type: object
    properties:
      pagination:
        type: object
        properties:
          next_key:
            type: string
            format: byte
          total:
            type: string
            format: uint64
      intents:
        type: array
        items:
          type: object
          properties:
            intent:
              type: object
              properties:
                id:
                  type: string
                  format: uint64
                name:
                  type: string
                intent:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
            metadata:
              type: object
              properties:
                '@type':
                  type: string
              additionalProperties: {}
  QueryParamsResponse:
    type: object
    properties:
      params:
        type: object
  MsgApproveActionResponse:
    type: object
    properties:
      status:
        type: string
  MsgNewIntentResponse:
    type: object
    properties:
      id:
        type: string
        format: uint64
  MsgRevokeActionResponse:
    type: object
  MsgUpdateParamsResponse:
    type: object
