protocol:
  - warden/**

protobuf:
  - warden/proto/**

sdk-module:
  - warden/x/warden/**
  - warden/proto/warden/warden/**

intent:
  - warden/x/intent/**
  - warden/proto/warden/intent/**

test:
  - '**/*_test.go'

docs:
  - docs/**

go-client:
  - go-client/**

keychain:
  - keychain/**

spaceward:
  - web/**
  - spaceward/**
