version: 1
build:
  main: warden/cmd/wardend
  binary: wardend
accounts:
- name: alice
  coins:
  - 200000000nward
- name: bob
  coins:
  - 100000000nward
client:
  openapi:
    path: docs/static/openapi.yml
  typescript:
    path: "../web/src/ts-client"
  hooks:
    path: "../web/src/ignite-hooks"
faucet:
  name: bob
  coins:
  - 100000nward
validators:
- name: alice
  bonded: 100000000nward
  home: ~/.warden
genesis:
  app_state:
    staking:
      params:
        bond_denom: "nward"

