port: 8080
path: db
loglevel: debug
logformat: plain
logtofile: false
keychain: "wardenkeychain14a2hpadpsy9h55wuja0"
chainid: "wardenprotocol"
wardenurl: localhost:9090
mnemonic: "exclude try nephew main caught favorite tone degree lottery device tissue tent ugly mouse pelican gasp lava flush pen river noise remind balcony emerge"
password: "password"
