version: '3.7'

services:

  warden:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-package
      target: wardend
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
        GITLAB_TOKEN: $GITLAB_TOKEN
    volumes:
      - ~/.wardend:/root/.wardend
    ports:
      - "26657:26657"
      - "9090:9090"
      - "1317:1317"
    environment:
      WARDEND_API_ENABLE: "true"
      WARDEND_API_ADDRESS: "tcp://0.0.0.0:1317"
      WARDEND_API_ENABLED_UNSAFE_CORS: "true"
      WARDEND_GRPC_ADDRESS: "0.0.0.0:9090"
      WARDEND_RPC_LADDR: "tcp://0.0.0.0:26657"

  faucet:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-package
      target: faucet
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
        GITLAB_TOKEN: $GITLAB_TOKEN
    ports:
      - "8000:8000"
    environment:
      NODE: http://warden:26657
      MNEMONIC: "exclude try nephew main caught favorite tone degree lottery device tissue tent ugly mouse pelican gasp lava flush pen river noise remind balcony emerge"

  web:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-package
      target: web
      args:
        FAUCET_URL: "http://127.0.0.1:8000"
        WARDEN_RPC_URL: "http://127.0.0.1:26657"
        WARDEN_REST_URL: "http://127.0.0.1:1317"
    ports:
      - "3000:80"
