---
name: Build and Push Docker

on:
  release:
    types:
      - published

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: |
       startsWith(github.ref_name, 'faucet@') ||
       startsWith(github.ref_name, 'wardend@') ||
       startsWith(github.ref_name, 'web@') ||
       startsWith(github.ref_name, 'wardenkms@') ||
       startsWith(github.ref_name, 'fwardenmodel@') ||
       startsWith(github.ref_name, 'mpcwardenmodel@') ||
       startsWith(github.ref_name, 'mpc-relayer@') ||
       startsWith(github.ref_name, 'relayer-eth@')
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          aws-region: eu-west-1
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      - name: Set tags
        id: vars
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "BUILD_DATE=$(git show -s --format=%ci ${{ env.COMMIT_SHA }})" >> $GITHUB_ENV
          echo "TAG=$(echo ${GITHUB_REF_NAME} | cut -d'@' -f2)" >> $GITHUB_ENV
          echo "REF=$(echo ${GITHUB_REF_NAME} | cut -d'@' -f1)" >> $GITHUB_ENV
          echo "ECR_REPO=${{ vars.ECR_REGISTRY }}.dkr.ecr.eu-west-1.amazonaws.com/wardenprotocol/production/$(echo ${{ github.ref_name }} | awk -F'@' '{print $1}')" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        id: image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile-${{ env.REF }}
          build-args: |
             SERVICE=${{ env.REF }}
             GIT_SHA=${{ env.COMMIT_SHA }}
             BUILD_DATE=${{ env.BUILD_DATE }}
          push: true
          tags: |
            ${{ env.ECR_REPO }}:${{ env.SHORT_SHA }}
            ${{ env.ECR_REPO }}:${{ env.TAG }}
            ${{ env.ECR_REPO }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
